### ISSUE TITLE
Combine implementations of map, DB, and UI together

### ISSUE THREAD

**Issue by austins** [angelicrf/thumbtack#19]
_Below text is from @Mike-Diaz's draft PR, moved to this issue to clearer show the progress:_

Implement `react-maps`, and `react-native-local-mongodb` into components Locations and NewLocation. Refactor Home components as Map to output a map component. Ensure locations are being saved to the database and the database persists on app reload or app closure. Ensure the map is being monitored for onPress events in order to pull coordinates and save them in `NewLocation.js` component. 

### To-do for this issue from this point:

- [x] Find a way for the marker to show up when the onPress event is called in the NewLocations component.
- [x] Figure out how to pass the values of what is being input in the name and notes sections of the LocationFormInputs component in order to save to the db.
- [x] Enable "Get My Coordinates" in order to pull current location if user wishes to save their own location instead of a picked location on the map inside the NewLocation component.
- [x] Link ApproximateAddress component output (ie. the address) to NewLocation component so that it can actually be saved and not just displayed.
- [x] Enable region to set to the correct marker selected.
- [x] Enable the map contained within the Locations component to update and display new markers after a marker is added from NewLocation component.
- [x] Add a card in the Locations component which re-renders when a marker is selected with the appropriate information and move the button to edit that marker to the card.
- [x] Finish implementing the EditLocations component in order to update the db correctly.

Note: This issue is incomplete. Please do not merge feat/implement-map-db-ui with master until all changes are made.

`Locations` Component showing multiple markers mapped from locations array inside DB: Placeholder only.
![Locations](https://user-images.githubusercontent.com/21978807/84123855-43eb6680-a9ef-11ea-8547-f0809f8d3277.JPG)

Map shown in `NewLocation` component. Currently not pulling coordinates from map:
![NewLocation](https://user-images.githubusercontent.com/21978807/84123966-6aa99d00-a9ef-11ea-8e06-a0c1424de5ac.JPG)

**Comment by austins** [comment]
See new commits: 24fd474cfb49d92ba46ed2e538e9ac68fbb77d40 and 68debf1bb151356849227ef8d4ac63a9c7544e3d.

Quick summary of changes with these commits: various bug fixes, passing of selected location (marker) from Locations to EditLocations, EditLocations update and delete functionality fully implemented, ApproximateLocation improvements, improved permission prompt flow, cleaned up source code files, reorganized files into src folder and other folders, only Android (removed references to iOS), updated app name string (capitalize first letter in Thumbtack), DB logic moved to LocationService, etc.
